apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: gitops
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: {{ .Values.repoURL }}
    path: .
    targetRevision: {{ .Values.targetRevision }}
    helm:
      releaseName: argo
      valueFiles:
      - values/values-gitops.yaml