{{- if .Values.features.cert-manager }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: 'in-cluster'
    namespace: 'cert-manager'
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: 1.9.1
    chart: cert-manager
    helm:
      releaseName: cert-manager
      valueFiles:
      - values/values-cert-manager.yaml
  project: 'system'
{{- end }}