{{- if (get .Values.features "cert-manager") }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: 'in-cluster'
    namespace: 'cert-manager'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: 1.10.0
    chart: cert-manager
    helm:
      skipCrds: false
      releaseName: cert-manager
      values: |-
{{ .Files.Get "values/values-cert-manager.yaml" | indent 8}} 
  project: 'system'
{{- end }}