{{- if .Values.features.ingress-nginx }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  labels:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: 'in-cluster'
    namespace: 'ingress-controller'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.4.0
    chart: ingress-nginx
    helm:
      releaseName: nginx
      valueFiles:
      - values/values-nginx.yaml
      parameters:
        - name: controller.service.loadBalancerIP
          value: {{ .Values.ingressIP }}
  project: 'system'

{{- end }}