{{- if .Values.features.prometheus }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: 'in-cluster'
    namespace: 'monitoring'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 41.9.0
    chart: kube-prometheus-stack
    helm:
      releaseName: prometheus
      valueFiles:
      - values/values-prometheus.yaml
  project: 'system'

{{- end }}