{{- if .Values.features.prometheus }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: system
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-41.9.0
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: 'in-cluster'
    namespace: 'monitoring'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 41.9.0
    chart: kube-prometheus-stack
    helm:
      skipCrds: true
      releaseName: prometheus
      values: |-
{{ .Files.Get "values/values-prom-operator.yaml" | indent 8}}
  project: 'system'

{{- end }}