apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
  name: gitops
  namespace: argocd
status: {}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'argocd'
      server: 'in-cluster'
  sourceRepos:
    - '*'
