apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: argoproj.io
      kind: '*'
  destinations:
    - namespace: 'monitoring'
      name: '*'
    - namespace: 'ingress-controller'
      name: '*'
    - namespace: 'cert-manager'
      name: '*'
    - namespace: 'kube-system'
      name: '*'
  sourceRepos:
    - '*'
